### PR TITLE
Linux client

### PR DESCRIPTION
**Pull request by pollend**
At the moment i'm just trying to get the client to work under linux and the current state is almost working. I've rewritten the UI in GTK sharp and currently also thinking about looking into Glade. I'm pretty new to GTK so the current state of the code base may not be ideal. The UI is a bit different, but i think it looks good enough. I also plan to rewrite the code to better conform to your code more.

Problems

-installing protocol and generally a way to install a mod. At the moment I'm just hacking in a bit of installation code.

- i'm getting this error when i attempt to start the game with a mod installed -- is never assigned to, and will always have its default value `0'

### CODE REVIEW

**Comment by ikkentim** [comment]
Thanks a lot for your PR! I'll check it out after Christmas is over.

**Comment by pollend** [comment]
opps, looks like i reintroduced a regression. I had to downgrade the .net version to 3.5. I'm not sure how to fix this for the linux build of the application. some of the UI elements look a bit funny on windows , but the original application should work as well.

**Comment by pollend** [comment]
Looks like the only feature that doesn't work is the protocol. I'm not sure how to work around this given the differences between linux distributions. This might be resolved with packaging, but i'm not familiar enough with packaging linux software. I'll probably look into this for the next couple of days. :+1:

**Comment by ikkentim** [comment]
I'll check it out now. I must say there are a couple of small issues but I'll get to that.

Anyways, thanks again for the amount of time your putting into this!

**Comment by ikkentim** [comment]
**Please take this as some constructive critisism. Again I'm thankful for the work you put into this, but there are a few things you should know about the changes you made and PRs in general**

This Pull Request
----------------------
- You committed OS files: `.directory`, `images/.directory` , ... might have missed a few
- You remove some essential parts from `src/ParkitectNexus.Client-mac/ParkitectNexus Client.csproj`. Seeing this PR has nothing to do with the Mac OS X client, this file should be left untouched.
- Because I'd prefer to create OS specific front ends, the GTK client will only be used for Linux. The WinForms front end will remain the front end for Windows
- Not really an error on your part (more the lack of documentation on this matter) but still a bit of an issue:
  - `ParkitectNexusClient-xamarin.sln` (used in Xamarin Studio) includes the `-xamarin` version of each csproj file (except the OS X client which only has 1 csproj file) because Xamarin/VS csproj files are not compatible
  - `ParkitectNexusClient.sln` (used in Visual Studio) includes the normal version of each csproj file, exept the OS X client, which it does not include.
  - You seem to have used the Xamarin solution. Maybe add it to the VS solution too (would require separate csproj files
- Please use 4 spaces instead of tabs!
- Ugh. I hate line endings. I'll fix that myself after the PR is merged
- I use C# 6.0 features, such as getter only properties, please don't change this!
- You added a `HintPath` to `System.Core` in `src/ParkitectNexus.Data/ParkitectNexus.Data-xamarin.csproj`, please don't.
- You added a reference to `UnityEngine` in `src/ParkitectNexus.Data/ParkitectNexus.Data.csproj`, please don't.
- Though I appreciate the trying to improve the code by adding a DataContract to ParkitectNexus.Data.Settings.GameSettings, it now isn't backwards compatible anymore with older setting files.
- You made the `_path` field of `ParkitectNexus.Data.Settings.SettingsBase` protected. Why? IMO fields should never be anything other than private. Besides, I don't think it is necessary anyways.
- Please paste all game DLLs in the `game` folder in the repo. `game/.gitignore` contains ignore rules for all `*.dll` file, so you can't push the DLLs by accident. This is done so the mod loader compiles on every machine. You changed the `HintPath` values in `src/ParkitectNexus.Mod.ModLoader/ParkitectNexus.Mod.ModLoader-xamarin.csproj` to machine specific values. You also added references to `System`, `Newtonsoft.Json` and `System.Core` to this project file. Why? You haven't even changed anything in the mod loader.
- You added an unnecessary reference to `DotNETUtilities` in `src/ParkitectNexusClient/ParkitectNexus.Client.csproj`.
- In my eyes all the changes you made to files within `src/ParkitectNexusClient/` are unneeded/unwanted.

Pull Requests in general
-------------------------------
As far as I can see this is the first PR of size you've ever made. I have a few general tips and hints for you for when you are making a pull request:

- **Stick to the scope!** In the case of this PR, the scope was to add a Linux client to the repository. You did this, but in the long run also made changes all over the place. Most likely your intentions were good, but it's better to stick to your scope (the Linux client) and only make changes necessary for accomplishing your goal. If there are multiple features/changes you thing need to be implemented, create multiple PRs.
- **Review your changes before committing!** You've committed a bunch of things I'm sure you didn't mean to, this includes changes to project files you didn't need or want to touch and you added `.directory` files in various locations. If you review your changes before you commit them, these mishaps are less likely to occur.
- **Add files added by your platform or non-project specific tool to your global `.gitignore` file!** I'm talking about the `.directory` files, obviously.
- **If a project you clone doesn't compile, it's an error on your end, not the code!** Apparently your compiler does not support C#6.0 features, instead of upgrading your compiler you changed the code. These are unwanted changes in the eyes of a repository maintainer.
- **Keep the number of commits to a minimum** Project maintainers don't like to see 10-s of commits in a single PR and will often ask you to squash your commits. Here's a useful article on squashing: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by ikkentim** [comment]
Replaced with #7

**Pull request closed without merging**
