### PR TITLE
Unit testing for web component

### PR DESCRIPTION
**Pull request by pollend**
I started adding some unit testing to the data portion of the application. I'll check in a bit everyday and you can review the changes. This way I don't add changes you don't want and the end client should be a bit more reliable with future features. :+1: the only thing I couldn't really test was DownloadFile function. I couldn't really decouple ParkitectNexusWebClient without substantial changes to codebase. At the moment there isn't too much to unit test, but you seem to be looking into adding quite a few feature in the near future.

I think quite a few of your more data dependent items should be moved out of the client and to the data component of the project. The Client component portions of the application should be restricted to being more of a frontend. This should make updating substantially easier in the future. 

I currently don't like the way I implemented the unit test for the assetrepository. the protected function is missing in terms of coverage.

You could also think about separating out your web service calls to the website.

### CODE REVIEW

**Comment by ikkentim** [comment]
:+1:

**Comment by ikkentim** [comment]
I've you feel like adding more unit tests, just open a new PR :)

**Comment by pollend** [comment]
I'm having some problems in terms of how you declare dependenct objects within some of your functions. I really can't mock these objects if they are self contained in a function. can we implement most of your data dependent objects under a base service. I can mock these components and test by this means. At the moment it's pretty near impossibly to test some of these functions without changes. I would look into dependency injection.

**Comment by ikkentim** [comment]
Could you give me a few examples of the situation you're talking about, and a suggestion on how to improve it?

**Comment by pollend** [comment]
something like this would be hard to unit test. I can't really mock ParkitectNexusWebClient in this state because it's self contained within this function. 

http://stackoverflow.com/questions/7739226/on-dependencies-in-unit-testing

public async Task<IParkitectAsset> DownloadFile(IParkitectNexusUrl url)
        {
            if (url == null) throw new ArgumentNullException(nameof(url));

            // Create a download url based on the file hash.
            var downloadInfo = await ResolveDownloadInfo(url);

            // Create a web client which will download the file.
            using (var webClient = new ParkitectNexusWebClient())
            {
...

}

}

**Comment by ikkentim** [comment]
I've created an issue so not to forget about it. Will look into it.

**Pull request merged**
