### PR TITLE
Issue compiling

### PR DESCRIPTION
**Pull request by pollend**
- I fixed the problem where the linux client constantly ask for the parkitect path
- I also fixed the problem where the images are offset in the nexus client. It's a fairly roundabout solution but it works.
- I also fixed the complication issue in mono. not sure what it was but i believe it was a problem with configuration using .net 4.0 dependencies over 4.5 odd. might be a bug in monodevelop no doubt, but remaking the project seems to have fixed that.

image

### CODE REVIEW

**Comment by pollend** [comment]
here is one more tweak 
image

**Comment by ikkentim** [comment]
Code looks good, except for the spaces before all function call brackets `FunctionName (args)` should be `FunctionName(args)`.

Will need to test it on mac and win still

**Comment by pollend** [comment]
fixed one more small problem, apparently the return before #!/bin/bash caused the bash script to not run correctly.

**Comment by ikkentim** [comment]
I know I'm very late to the party, but just letting you know this PR breaks the clicking events

**Comment by pollend** [comment]
the clicking events?

**Comment by ikkentim** [comment]
jup

**Comment by pollend** [comment]
can you give me some details?

**Comment by pollend** [comment]
Don't I  just use the old codepath if it isn't linux? It should run the same way as it did on windows.

**Pull request closed without merging**
